In [ ]:
import pandas as pd # importinbg libraries

In [8]:
df = pd.read_csv("bhatbhateni_sales.csv") #loading dataset
print(df.head()) # first five rows
print(df.shape) # rows & columns
print(df.dtypes) # datatypes 
print(df.describe(include="all")) # summary statistics
print(df.isnull().sum()) # checking null values
print(df.duplicated().sum()) # number of duplicates

  TransactionID        Date CustomerID    CustomerName  \
0     TXN101590  2025-05-19   CUST1100  Sujan Shrestha
1     TXN103282  2025-03-07   CUST1005      Milan Lama
2     TXN103539  2025-10-05   CUST1130       Alina Rai
3     TXN102479  2025-11-12   CUST1057      Neha Karki
4     TXN104408  2025-10-09   CUST1005      Milan Lama

                     Branch ProductCategory           ProductName  Quantity  \
0        Pokhara - Lakeside          Bakery  Chocolate Cake Slice         2
1    Butwal - Traffic Chowk   Personal Care             Dove Soap         3
2  Bhaktapur - Suryabinayak         Apparel         Winter Jacket         4
3      Kathmandu - New Road       Household        Surf Excel 1kg         4
4    Butwal - Traffic Chowk       Beverages  Gorkha Beer (6-pack)         2

   UnitPrice  TotalAmount PaymentMethod
0     171.29       342.58        Khalti
1     149.59       448.77         eSewa
2    2794.25     11177.00        Khalti
3     399.62      1598.48          Cash
4     281.01       562.02         eSewa
(18812, 11)
TransactionID          str
Date                   str
CustomerID             str
CustomerName           str
Branch                 str
ProductCategory        str
ProductName            str
Quantity             int64
UnitPrice          float64
TotalAmount        float64
PaymentMethod          str
dtype: object
       TransactionID        Date CustomerID CustomerName  \
count          18812       18812      18812        18244
unique          6000         365        147          116
top        TXN103822  2025-09-30   CUST1002    Alina Rai
freq               7         142        685          666
mean             NaN         NaN        NaN          NaN
std              NaN         NaN        NaN          NaN
min              NaN         NaN        NaN          NaN
25%              NaN         NaN        NaN          NaN
50%              NaN         NaN        NaN          NaN
75%              NaN         NaN        NaN          NaN
max              NaN         NaN        NaN          NaN

                       Branch ProductCategory         ProductName  \
count                   18812           18530               18812
unique                      8               8                  41
top     Kathmandu - Kupondole         Grocery  Sanitary Pads Pack
freq                     3391            3146                 502
mean                      NaN             NaN                 NaN
std                       NaN             NaN                 NaN
min                       NaN             NaN                 NaN
25%                       NaN             NaN                 NaN
50%                       NaN             NaN                 NaN
75%                       NaN             NaN                 NaN
max                       NaN             NaN                 NaN

            Quantity     UnitPrice   TotalAmount PaymentMethod
count   18812.000000  18441.000000  18812.000000         18344
unique           NaN           NaN           NaN             5
top              NaN           NaN           NaN          Cash
freq             NaN           NaN           NaN          6464
mean        2.506804    728.803530   1819.990565           NaN
std         1.114328    766.346109   2241.968350           NaN
min         1.000000     40.140000     40.610000           NaN
25%         2.000000    240.160000    488.397500           NaN
50%         3.000000    416.780000    989.000000           NaN
75%         3.000000    848.320000   2142.545000           NaN
max         4.000000   3499.280000  13997.120000           NaN
TransactionID        0
Date                 0
CustomerID           0
CustomerName       568
Branch               0
ProductCategory    282
ProductName          0
Quantity             0
UnitPrice          371
TotalAmount          0
PaymentMethod      468
dtype: int64
724

In [13]:
true_duplicates_mask = df.duplicated(keep=False) # this keeps the true duplicates
true_duplicates = df[true_duplicates_mask]
print(true_duplicates)

      TransactionID        Date CustomerID      CustomerName  \
7         TXN104948  2025-11-01   CUST1098      Bijay Khadka
13        TXN105458  2025-10-01   CUST1096      Sabnam Magar
17        TXN101525  2025-07-06   CUST1003    Kiran Adhikari
28        TXN101202  2025-12-26   CUST1135  Sabina Bhattarai
43        TXN103224  2025-10-09   CUST1093     Aashish Magar
...             ...         ...        ...               ...
18731     TXN100260  2025-01-13   CUST1067    Anita Shrestha
18746     TXN100216  2025-09-23   CUST1103       Rohit Thapa
18767     TXN102820  2025-10-27   CUST1108        Neha Karki
18778     TXN105330  2025-02-12   CUST1009        Sushma Rai
18793     TXN103345  2025-07-28   CUST1069       Bijay Magar

                         Branch ProductCategory             ProductName  \
7      Bhaktapur - Suryabinayak             NaN        USB Cable Type-C
13           Pokhara - Lakeside   Personal Care      Sanitary Pads Pack
17        Kathmandu - Kupondole         Grocery               Sugar 1kg
28          Lalitpur - Pulchowk       Beverages  Tea Leaves (Ilam) 250g
43     Bhaktapur - Suryabinayak       Beverages     Nescafe Coffee 100g
...                         ...             ...                     ...
18731     Kathmandu - Kupondole         Grocery                Salt 1kg
18746    Butwal - Traffic Chowk          Bakery          Butter Cookies
18767  Bhaktapur - Suryabinayak       Beverages  Tea Leaves (Ilam) 250g
18778      Kathmandu - New Road       Household             LED Bulb 9W
18793       Lalitpur - Pulchowk         Grocery               Sugar 1kg

       Quantity  UnitPrice  TotalAmount      PaymentMethod
7             4    1630.72      6522.88               Cash
13            1     290.43       290.43              eSewa
17            4     367.14      1468.56             Khalti
28            4     396.14      1584.56             Khalti
43            1     129.98       129.98               Cash
...         ...        ...          ...                ...
18731         4     172.98       691.92             Khalti
18746         1     256.45       256.45               Cash
18767         2     437.05       874.10  Debit/Credit Card
18778         2     603.70      1207.40             Khalti
18793         3     655.15      1965.45             Khalti

[1448 rows x 11 columns]

In [12]:
multi_item_mask = df.duplicated(subset=['TransactionID'], keep=False)
multi_items = df[multi_item_mask]
print(multi_items)

      TransactionID        Date CustomerID       CustomerName  \
0         TXN101590  2025-05-19   CUST1100     Sujan Shrestha
1         TXN103282  2025-03-07   CUST1005         Milan Lama
2         TXN103539  2025-10-05   CUST1130          Alina Rai
3         TXN102479  2025-11-12   CUST1057         Neha Karki
4         TXN104408  2025-10-09   CUST1005         Milan Lama
...             ...         ...        ...                ...
18807     TXN102758  2025-09-22   CUST1110       Sushma Karki
18808     TXN105279  2025-12-14   CUST1031      Sabnam Khadka
18809     TXN102971  2025-05-11   CUST1002  Kritika Bhattarai
18810     TXN101435  2025-10-06   CUST1031                NaN
18811     TXN105017  2025-01-07   CUST1136      Bikash Gurung

                         Branch ProductCategory           ProductName  \
0            Pokhara - Lakeside          Bakery  Chocolate Cake Slice
1        Butwal - Traffic Chowk   Personal Care             Dove Soap
2      Bhaktapur - Suryabinayak         Apparel         Winter Jacket
3          Kathmandu - New Road       Household        Surf Excel 1kg
4        Butwal - Traffic Chowk       Beverages  Gorkha Beer (6-pack)
...                         ...             ...                   ...
18807      Kathmandu - New Road     Electronics      USB Cable Type-C
18808  Bhaktapur - Suryabinayak         Grocery             Sugar 1kg
18809    Butwal - Traffic Chowk           Dairy           DDC Milk 1L
18810  Bhaktapur - Suryabinayak     Electronics            Wall Clock
18811  Bhaktapur - Suryabinayak     Electronics   Power Bank 10000mAh

       Quantity  UnitPrice  TotalAmount      PaymentMethod
0             2     171.29       342.58             Khalti
1             3     149.59       448.77              eSewa
2             4    2794.25     11177.00             Khalti
3             4     399.62      1598.48               Cash
4             2     281.01       562.02              eSewa
...         ...        ...          ...                ...
18807         1     429.82       429.82               Cash
18808         1     546.90       546.90               Cash
18809         3     129.40       388.20  Debit/Credit Card
18810         2     781.61      1563.22               Cash
18811         4    3280.42     13121.68               Cash

[17672 rows x 11 columns]

## Before and After Cleaning ##

In [14]:
dataset_before = len(df)
dataset_before

18812

In [15]:
cleaned_dataset = df.drop_duplicates()
rows_after = len(cleaned_dataset)
cleaned_dataset

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod
0,TXN101590,2025-05-19,CUST1100,Sujan Shrestha,Pokhara - Lakeside,Bakery,Chocolate Cake Slice,2,171.29,342.58,Khalti
1,TXN103282,2025-03-07,CUST1005,Milan Lama,Butwal - Traffic Chowk,Personal Care,Dove Soap,3,149.59,448.77,eSewa
2,TXN103539,2025-10-05,CUST1130,Alina Rai,Bhaktapur - Suryabinayak,Apparel,Winter Jacket,4,2794.25,11177.00,Khalti
3,TXN102479,2025-11-12,CUST1057,Neha Karki,Kathmandu - New Road,Household,Surf Excel 1kg,4,399.62,1598.48,Cash
4,TXN104408,2025-10-09,CUST1005,Milan Lama,Butwal - Traffic Chowk,Beverages,Gorkha Beer (6-pack),2,281.01,562.02,eSewa
...,...,...,...,...,...,...,...,...,...,...,...
18807,TXN102758,2025-09-22,CUST1110,Sushma Karki,Kathmandu - New Road,Electronics,USB Cable Type-C,1,429.82,429.82,Cash
18808,TXN105279,2025-12-14,CUST1031,Sabnam Khadka,Bhaktapur - Suryabinayak,Grocery,Sugar 1kg,1,546.90,546.90,Cash
18809,TXN102971,2025-05-11,CUST1002,Kritika Bhattarai,Butwal - Traffic Chowk,Dairy,DDC Milk 1L,3,129.40,388.20,Debit/Credit Card
18810,TXN101435,2025-10-06,CUST1031,NaN,Bhaktapur - Suryabinayak,Electronics,Wall Clock,2,781.61,1563.22,Cash
18811,TXN105017,2025-01-07,CUST1136,Bikash Gurung,Bhaktapur - Suryabinayak,Electronics,Power Bank 10000mAh,4,3280.42,13121.68,Cash

## Handling Missing Values ##

In [16]:
df.head()

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod
0,TXN101590,2025-05-19,CUST1100,Sujan Shrestha,Pokhara - Lakeside,Bakery,Chocolate Cake Slice,2,171.29,342.58,Khalti
1,TXN103282,2025-03-07,CUST1005,Milan Lama,Butwal - Traffic Chowk,Personal Care,Dove Soap,3,149.59,448.77,eSewa
2,TXN103539,2025-10-05,CUST1130,Alina Rai,Bhaktapur - Suryabinayak,Apparel,Winter Jacket,4,2794.25,11177.00,Khalti
3,TXN102479,2025-11-12,CUST1057,Neha Karki,Kathmandu - New Road,Household,Surf Excel 1kg,4,399.62,1598.48,Cash
4,TXN104408,2025-10-09,CUST1005,Milan Lama,Butwal - Traffic Chowk,Beverages,Gorkha Beer (6-pack),2,281.01,562.02,eSewa

In [ ]:
# filling the customer name as missing
df["CustomerName"]=df["CustomerName"].fillna('missing')

In [ ]:
# finding the most repetitive product category
df["ProductCategory"].describe(include="all")

count       18530
unique          8
top       Grocery
freq         3146
Name: ProductCategory, dtype: object

In [23]:
most_frequent = df['ProductCategory'].value_counts().index[0]
most_frequent

'Grocery'

In [37]:
# filling the missing product category by the most repetitive purchase
df["ProductCategory"]=df["ProductCategory"].fillna('Grocery')

In [38]:
df["UnitPrice"] = df["UnitPrice"].fillna(
    df["TotalAmount"] / df["Quantity"]
)

In [31]:
df['PaymentMethod'] = df['PaymentMethod'].fillna('Unknown')

In [39]:
print(df.isnull().sum())

TransactionID      0
Date               0
CustomerID         0
CustomerName       0
Branch             0
ProductCategory    0
ProductName        0
Quantity           0
UnitPrice          0
TotalAmount        0
PaymentMethod      0
ProductCatgory     0
dtype: int64

## Formatting the Date Time Column ##