## Analyzing Banking Dataset ##

Loading the dataset

In [1]:
import pandas as pd

Basic viewing of data

In [3]:
df = pd.read_csv("nepal_bank_transactions.csv")
df.head()

,transaction_id,date,time,branch_name,district,channel,transaction_type,card_type,account_type,amount_npr,response_code,response_message,transaction_status,customer_age,customer_gender,processing_time_ms
0,TXN0000001,2024-01-01,00:43:34,New Baneshwor,Kathmandu,ATM,Mini Statement,Credit Card,Current,0.00,0,Approved,Success,26.0,Female,1322
1,TXN0000002,2024-01-01,01:04:46,Dhangadhi Branch,Kailali,Internet Banking,Statement Download,NaN,Savings,0.00,0,Approved,Success,30.0,NaN,711
2,TXN0000003,2024-01-01,06:41:33,Hetauda Branch,Makwanpur,ATM,PIN Change,Debit Card,Savings,0.00,0,Approved,Success,58.0,Female,1633
3,TXN0000004,2024-01-01,07:46:42,Butwal Branch,Rupandehi,Mobile Banking,Fund Transfer,NaN,Savings,97651.24,0,Approved,Success,56.0,Female,816
4,TXN0000005,2024-01-01,08:44:14,Janakpur Branch,Dhanusha,ATM,Mini Statement,Debit Card,Savings,0.00,0,Approved,Success,37.0,Male,1168

In [4]:
df.describe(include="all")

,transaction_id,date,time,branch_name,district,channel,transaction_type,card_type,account_type,amount_npr,response_code,response_message,transaction_status,customer_age,customer_gender,processing_time_ms
count,6060,6060,6060,6060,6060,6060,6060,3461,6060,6060.000000,6060.000000,6060,6060,5941.000000,5968,6060.000000
unique,6000,366,5743,45,13,10,13,3,3,NaN,NaN,8,4,NaN,2,NaN
top,TXN0000041,2024-04-05,11:33:25,Bhaktapur Branch,Kathmandu,ATM,Balance Inquiry,Debit Card,Savings,NaN,NaN,Approved,Success,NaN,Female,NaN
freq,2,38,3,416,816,2347,1040,2791,4758,NaN,NaN,5431,5431,NaN,3094,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8586.476797,6.142244,NaN,NaN,34.737755,NaN,835.182508
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20667.251508,19.742012,NaN,NaN,11.414471,NaN,425.068837
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-20000.000000,0.000000,NaN,NaN,0.000000,NaN,80.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,26.000000,NaN,524.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,0.000000,NaN,NaN,34.000000,NaN,754.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7306.665000,0.000000,NaN,NaN,42.000000,NaN,1093.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198498.260000,96.000000,NaN,NaN,150.000000,NaN,2479.000000

In [9]:
df.shape
print(f"rows: {df.shape[0]}")
print(f"cols: {df.shape[1]}")

rows: 6060
cols: 16

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6060 entries, 0 to 6059
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      6060 non-null   object
 1   date                6060 non-null   object
 2   time                6060 non-null   object
 3   branch_name         6060 non-null   object
 4   district            6060 non-null   object
 5   channel             6060 non-null   object
 6   transaction_type    6060 non-null   object
 7   card_type           3461 non-null   object
 8   account_type        6060 non-null   object
 9   amount_npr          6060 non-null   float64
 10  response_code       6060 non-null   int64
 11  response_message    6060 non-null   object
 12  transaction_status  6060 non-null   object
 13  customer_age        5941 non-null   float64
 14  customer_gender     5968 non-null   object
 15  processing_time_ms  6060 non-null   int64
dtypes: float64(2), int64(2), object(12)
memory usage: 757.6+ KB

In [11]:
print(df.loc[0,"branch_name"])
print(df.iloc[0,3])
df.loc[0:2,["branch_name","channel","transaction_status"]]

New Baneshwor
New Baneshwor

        branch_name           channel transaction_status
0     New Baneshwor               ATM            Success
1  Dhangadhi Branch  Internet Banking            Success
2    Hetauda Branch               ATM            Success